#-------------------------
# Staging Image
#-------------------------
FROM balenalib/{{ platform }}-debian:stretch-build-20190215 as build

# Install Packages for compilation
RUN install_packages wget zlib1g-dev libbz2-dev libssl-dev libffi-dev

# compile python3
{% if cross_build %}
RUN [ "cross-build-start" ]
{% endif %}

# Compile Python 3
RUN mkdir -p /tmp/ && cd /tmp/ \
    && wget https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz \
    && tar -zxvf Python-3.6.8.tgz \
    && cd Python-3.6.8 \
    && ./configure --enable-shared \
    && make -j4 > make-python3.log 2> make-python3-error.log

RUN apt-get update && apt-get install sudo curl -y && mkdir -p /usr/tmp && cd /usr/tmp \
    && wget https://download.motesque.com/wiringPi-96344ff.tar.gz \
    && tar xfz wiringPi-96344ff.tar.gz \
    && cd wiringPi-96344ff \
    && ./build \
    && rm -rf /usr/tmp

{% if cross_build %}
RUN [ "cross-build-end" ]
{% endif %}

#-------------------------
# Runtime Image
#-------------------------
FROM balenalib/{{ platform }}-debian:stretch-run-20190215

RUN install_packages \
     make \
     cron \
     curl \
     dbus \
     ffmpeg \
     htop \ 
     less  \
     libcairo2  \
     libopenjp2-7 \
     libpango-1.0-0  \
     libpangocairo-1.0-0  \
     net-tools \
     netcat \
     nfs-common \
     ntp \
     openssl  \
     openssh-client \
     usbutils \
     vim \
     wget \
     zlib1g


# install microsoft contrib core fonts (Arial, Georgia etc)
RUN install_packages cabextract xfonts-utils \
    && wget http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.6_all.deb \
    && dpkg -i ttf-mscorefonts-installer_3.6_all.deb \
    && rm ttf-mscorefonts-installer_3.6_all.deb

{% if cross_build %}
RUN [ "cross-build-start" ]
{% endif %}

# copy and install Python 3
COPY --from=build /tmp/Python-3.6.8/ /tmp/Python-3.6.8/
RUN cd /tmp/Python-3.6.8/ \
    && make install \
    && cp libpython3.6m.so.1.0 /usr/lib/ \
    && cd /tmp/ \
    && rm -rf /tmp/Python-3.6.8/ \
    && pip3 install --upgrade wheel==0.33.6 pip==19.3.1

#RUN apt-get update && apt-get install -y \
#     curl \
#     dbus \
#     ffmpeg \
#     gfortran \
#     ghostscript \
#     htop \
#     jq \
#     libatlas-base-dev \
#     libbz2-dev \
#     libffi-dev \
#     libdbus-glib-1-dev \
#     libgdbm-dev \
#     libhdf5-dev \
#     libjpeg-dev \
#     liblapack-dev  \
#     libgirepository1.0-dev \
#     libncursesw5-dev \
#     libopenblas-dev \
#     libsqlite3-dev \
#     libssl-dev \
#     net-tools \
#     netcat \
#     nfs-common \
#     ntp \
#     openssl  \
#     pandoc \
#     tk-dev \
#     usbutils \
#     vim \
#     wget \
#     zlib1g-dev

COPY ./requirements.txt /usr/tmp/
RUN pip3 install  \
       --trusted-host pypi.motesque.com \
        --index-url http://pypi.motesque.com:8181 \
        --extra-index-url https://pypi.org/simple \
        --no-cache-dir \
        --no-deps --find-links . -r /usr/tmp/requirements.txt \
        && pip3 check

{% if cross_build %}
RUN [ "cross-build-end" ]
{% endif %}
