FROM balenalib/{{ platform }}-debian:stretch-build-20190215

# compile python3
{% if cross_build %}
RUN [ "cross-build-start" ]
{% endif %}

RUN mkdir -p /usr/tmp && cd /usr/tmp \
    && wget https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz \
    && tar -zxvf Python-3.6.8.tgz  \
    && cd Python-3.6.8  \
    && ./configure --enable-shared \
    && make -j4\
    && make install  \
    && rm -rf /usr/tmp

RUN apt-get update && apt-get install -y \
     curl \
     dbus \
     ffmpeg \
     gfortran \
     ghostscript \
     htop \
     jq \
     libatlas-base-dev \
     libbz2-dev \
     libffi-dev \
     libdbus-glib-1-dev \
     libgdbm-dev \
     libhdf5-dev \
     libjpeg-dev \
     liblapack-dev  \
     libgirepository1.0-dev \
     libncursesw5-dev \
     libopenblas-dev \
     libsqlite3-dev \
     libssl-dev \
     net-tools \
     netcat \
     nfs-common \
     ntp \
     openssl  \
     pandoc \
     tk-dev \
     usbutils \
     vim \
     wget \
     zlib1g-dev

RUN apt-get update && apt-get install sudo curl -y && mkdir -p /usr/tmp && cd /usr/tmp \
    && wget https://download.motesque.com/wiringPi-96344ff.tar.gz \
    && tar xfz wiringPi-96344ff.tar.gz \
    && cd wiringPi-96344ff \
    && ./build \
    && rm -rf /usr/tmp

COPY ./requirements_py3.txt /usr/tmp/
RUN pip3 install  --trusted-host pypi.motesque.com --index-url http://pypi.motesque.com:8181 --extra-index-url https://pypi.org/simple --find-links . -r /usr/tmp/requirements_py3.txt

{% if cross_build %}
RUN [ "cross-build-end" ]
{% endif %}
